[project]
name = "ascii-art-generator"
version = "0.1.0"
dependencies = [
    "Pillow",
    "numpy",
    "opencv-python",
    "rembg",
    "onnxruntime",
]

[project.scripts]
pyscii = "ascii_art_generator.main:main"
